### ISSUE TITLE
bcs-helm-manager 添加命令行工具

### ISSUE THREAD

**Issue by adevjoe** [TencentBlueKing/bk-bcs#2099]
### 需求

在现有命令行工具的基础上，更新下新的接口。现有命令行在 `internal/client`。
需要在 `internal/client` 目录添加使用文档。

功能列表：
- Available
- ListRepository
- GetRepository
- ListChartV1
- GetChartDetailV1
- GetVersionDetailV1
- DeleteChart
- DeleteChartVersion
- ListReleaseV1
- GetReleaseDetailV1
- InstallReleaseV1
- UninstallReleaseV1
- UpgradeReleaseV1
- RollbackReleaseV1
- GetReleaseHistory

### client 使用方法
这是现有的使用方法，使用文档需要比这个详细一些。

默认配置文件：`/etc/bcs/helmctl.yaml`

配置文件内容：
```
config:
  apiserver: "https://example.com:443"
  bcs_token: "$BCS_API_TOKEN"
  operator: "admin-T49e"
```

#### 检查联通性
```
bcs-helm-client available
```

#### 查看仓库列表
```
bcs-helm-client get repo -p project-1 -owide
```

#### 查看 Release 列表
```
bcs-helm-client get release --cluster BCS-K8S-00000 -n default
```

#### 部署应用
```
bcs-helm-client install release-name chart-name 0.1.2 -n default -p project -r repo --cluster BCS-K8S-00000 -f values.yaml
```
...
